### ISSUE TITLE
Demo - columns and column headers misaligned with scrollbar

### ISSUE THREAD

**Issue by williamcooney** [denisraslov/react-spreadsheet-grid#1] opened 2017-11-22 15:49 UTC
See the screenshot below (from Chrome).

Browsers tested:
Chrome 62.0
Firefox 57.0

Side note: Internet Explorer does not work at all (tested IE 11.0). Scripts throw an error and display a blank page. Not sure if you intend to support Internet Explorer at all.

Let me know if you need anymore information.

![ssapp1](https://user-images.githubusercontent.com/22821359/33136084-51fddc6c-cf72-11e7-829a-91c658cc4815.png)

**Comment by denisraslov** [comment] 2017-11-26 11:33
Hi @williamcooney!
Thank you for this issue!

Were Chrome and Firefox tested in Windows or in another OS?

**Comment by jimmyye** [comment] 2017-11-26 13:30
Same here in macOS.
Chrome 62
Firefox ESR 52

**Comment by denisraslov** [comment] 2017-11-26 22:24
Hi @jimmyye! Thank you.

I think, the problem is that the header doesn't have a scrollbar when the body has one. The fix will be to add a scrollbar to the header when it needed. 

Will be done in one of the next releases.

**Comment by williamcooney** [comment] 2017-11-29 04:11
Looks like you got it figured out already. Mine was on Windows by the way.

**Comment by denisraslov** [comment] 2017-12-08 18:11
The bug is fixed in the [**release 1.2.0**](https://github.com/denisraslov/react-spreadsheet-grid/releases/tag/1.2.0).
Now the header has a scrollbar too if there is a scroll in the table.

**Closed by denisraslov** 2017-12-08 18:11 UTC
Labels: bug, help wanted
